name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DoSomething
      run: |
        cat /etc/apt/sources.list
    - name: DoSomething
      run: |
        cat /etc/apt/sources.list.d/*
    - name: DoSomething
      run: |
        sudo apt-get -y build-dep gnumeric
